apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system-kubernetes-component
    labels:
    backstage.io/kubernetes-id: solar-system-kubernetes-component
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system-kubernetes-component
  template:
    metadata:
      labels:
        app: solar-system-kubernetes-component
        backstage.io/kubernetes-id: solar-system-kubernetes-component
    spec:
      containers:
      - name: solar-system
        image: borkarrohit/solar_system:latest
        ports:
        - containerPort: 3000
