apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
spec:
  type: LoadBalancer
  selector:
    app: solar-system-kubernetes-component
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000